# Generated by Django 2.2.4 on 2019-08-22 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=80)),
                ('members', models.ManyToManyField(null=True, related_name='chat_groups', to='branches.Branch')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='branches.Branch')),
            ],
            options={
                'unique_together': {('owner', 'id')},
            },
        ),
        migrations.CreateModel(
            name='BranchMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
                ('message_html', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.Branch')),
                ('branch_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='branchchat.BranchChat')),
            ],
        ),
        migrations.CreateModel(
            name='ChatVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('thumbnail', models.ImageField(height_field='height', null=True, upload_to='thumbnails', width_field='width')),
                ('video', models.FileField(null=True, upload_to='static/videos')),
                ('branch_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='branchchat.BranchMessage')),
            ],
        ),
        migrations.CreateModel(
            name='ChatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('image', models.ImageField(height_field='height', null=True, upload_to='static/images', width_field='width')),
                ('branch_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='branchchat.BranchMessage')),
            ],
        ),
    ]
