# Generated by Django 2.1.4 on 2018-12-09 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.Branch'),
        ),
    ]
