# Generated by Django 2.2.4 on 2019-08-29 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_auto_20190828_1835'),
        ('branchchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('on hold', 'On hold')], default='on hold', max_length=20)),
                ('branch_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='branchchat.BranchChat')),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_sent', to='branches.Branch')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_received', to='branches.Branch')),
            ],
            options={
                'unique_together': {('request_to', 'branch_chat')},
            },
        ),
    ]
