# Generated by Django 2.1.4 on 2019-07-12 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0014_branch_trending_score'),
        ('branchchat', '0002_auto_20181210_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('image', models.ImageField(height_field='height', null=True, upload_to='static/images', width_field='width')),
                ('branch_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='branchchat.BranchMessage')),
            ],
        ),
        migrations.CreateModel(
            name='ChatVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('thumbnail', models.ImageField(height_field='height', null=True, upload_to='thumbnails', width_field='width')),
                ('video', models.FileField(null=True, upload_to='static/videos')),
                ('branch_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='branchchat.BranchMessage')),
            ],
        ),
        migrations.RenameField(
            model_name='branchchat',
            old_name='branch',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='branchchat',
            name='members',
            field=models.ManyToManyField(null=True, related_name='chat_groups', to='branches.Branch'),
        ),
        migrations.AlterField(
            model_name='branchchat',
            name='name',
            field=models.CharField(default='default', max_length=25),
        ),
        migrations.RemoveField(
            model_name='branchchat',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='branchchat',
            unique_together={('owner', 'name')},
        ),
    ]
