# Generated by Django 2.2.4 on 2019-08-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchchat', '0002_chatrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchchat',
            name='image',
            field=models.ImageField(default='images/group_images/profile/default.jpeg', upload_to='images/chat_groups/profile_image'),
        ),
    ]
