# Generated by Django 2.2.4 on 2019-09-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchchat', '0003_branchchat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchchat',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
