# Generated by Django 2.1.4 on 2019-07-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0014_branch_trending_score'),
        ('branchchat', '0003_auto_20190712_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchchat',
            name='name',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='branchchat',
            unique_together={('owner', 'id')},
        ),
    ]
