# Generated by Django 2.1.4 on 2019-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchchat', '0004_auto_20190712_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmessage',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='branchmessage',
            name='message_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
