# Generated by Django 2.2.4 on 2019-09-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchchat', '0004_branchchat_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchchat',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/chat_groups/icons'),
        ),
    ]
