# Generated by Django 2.2.4 on 2020-02-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchchat', '0006_branchchat_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchchat',
            name='auto_invite_followers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchchat',
            name='type',
            field=models.CharField(choices=[('DR', 'Direct'), ('FO', 'Follow only'), ('PU', 'Public'), ('IO', 'Invite only')], default='DR', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='branchchat',
            constraint=models.UniqueConstraint(condition=models.Q(auto_invite_followers=True), fields=('owner', 'auto_invite_followers'), name='unique_auto_invite_followers_chat'),
        ),
    ]
