# Generated by Django 2.0 on 2018-07-06 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(default='images\\img.jpg', upload_to='images')),
                ('fake_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='fake_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
