# Generated by Django 2.0 on 2018-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180707_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
