# Generated by Django 2.0 on 2018-07-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180707_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeprofile',
            name='url',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
