# Generated by Django 2.0 on 2018-07-07 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fakeprofile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
