# Generated by Django 2.0 on 2018-07-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180724_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeprofile',
            name='url',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='url',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
