# Generated by Django 2.0 on 2018-10-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180727_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='/images/users/profile/default.jpeg', upload_to='images/users/profile'),
        ),
    ]
