# Generated by Django 2.1.4 on 2018-12-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181031_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Anon', max_length=24),
        ),
    ]
