# Generated by Django 2.1.4 on 2018-12-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181206_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakeprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FakeProfile',
        ),
    ]
