# Generated by Django 2.2.4 on 2019-08-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190106_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dummy',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
