# Generated by Django 2.1.4 on 2018-12-06 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('group_image', models.ImageField(default='/images/group_images/profile/default.jpeg', upload_to='images/group_images/profile')),
                ('group_banner', models.ImageField(default='/images/group_images/banner/default.jpeg', upload_to='images/group_images/banner')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='unnamed', max_length=30)),
                ('accessibility', models.CharField(choices=[('PU', 'Public'), ('IO', 'Invite only')], default='PU', max_length=2)),
                ('description', models.TextField(default='No description.', max_length=200)),
                ('over_18', models.BooleanField(default=False)),
                ('tag', models.IntegerField(blank=True, null=True)),
                ('uri', models.CharField(default=uuid.uuid4, max_length=60)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='branches.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='branches.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('owner', 'name')},
        ),
    ]
