# Generated by Django 2.2.4 on 2019-08-22 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_image', models.ImageField(default='/images/group_images/profile/default.jpeg', upload_to='images/group_images/profile')),
                ('branch_banner', models.ImageField(default='/images/group_images/banner/default.jpeg', upload_to='images/group_images/banner')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='unnamed', max_length=30)),
                ('accessibility', models.CharField(choices=[('PU', 'Public'), ('IO', 'Invite only')], default='PU', max_length=2)),
                ('description', models.TextField(blank=True, max_length=140, null=True)),
                ('over_18', models.BooleanField(default=False)),
                ('uri', models.CharField(default=uuid.uuid4, max_length=60, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('trending_score', models.DecimalField(decimal_places=5, default=0.0, max_digits=14)),
                ('follows', models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='branches.Branch')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='branches.Branch')),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='branches.Branch')),
                ('to_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='branches.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BranchRequest',
            fields=[
                ('type', models.CharField(blank=True, choices=[('add', 'Add'), ('remove', 'Remove')], max_length=20, null=True)),
                ('relation_type', models.CharField(blank=True, choices=[('parent', 'Parent'), ('child', 'Child')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('on hold', 'On hold')], default='on hold', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='branches.Branch')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='branches.Branch')),
            ],
            options={
                'unique_together': {('request_to', 'request_from', 'type')},
            },
        ),
    ]
