# Generated by Django 2.2.4 on 2019-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_banner',
            field=models.ImageField(default='/images/group_images/banner/default.png', upload_to='images/group_images/banner'),
        ),
    ]
