# Generated by Django 2.2.4 on 2019-08-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20190828_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_banner',
            field=models.ImageField(default='images/group_images/banner/default.png', upload_to='images/group_images/banner'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_image',
            field=models.ImageField(default='images/group_images/profile/default.jpeg', upload_to='images/group_images/profile'),
        ),
    ]
