# Generated by Django 2.1.4 on 2018-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20181210_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
