# Generated by Django 2.1.4 on 2018-12-15 22:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0003_branch_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('owner', 'name')},
        ),
    ]
