# Generated by Django 2.1.4 on 2019-01-06 20:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_auto_20181216_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 6, 20, 21, 33, 111431, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='from_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_branch', to='branches.Branch'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='to_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_branch', to='branches.Branch'),
        ),
    ]
