# Generated by Django 2.2.4 on 2019-12-04 14:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tags', '0001_initial'),
        ('branches', '0004_branch_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.GenericStringTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
