# Generated by Django 2.2.4 on 2019-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('US', 'User'), ('CM', 'Community'), ('HB', 'Hub')], default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_branchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_hostable',
            field=models.BooleanField(default=True),
        ),
    ]
