# Generated by Django 2.1.4 on 2019-02-15 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0005_auto_20190106_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='branches.Branch')),
                ('to_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='branches.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='from_branch',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='to_branch',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
