# Generated by Django 2.2.4 on 2019-12-09 23:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_auto_20191209_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.GenericStringTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
