# Generated by Django 2.1.4 on 2019-02-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_auto_20190215_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='follows',
            field=models.ManyToManyField(related_name='_branch_follows_+', to='branches.Branch'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='from_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='branches.Branch'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='to_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='branches.Branch'),
        ),
    ]
