# Generated by Django 2.1.4 on 2019-02-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_auto_20190216_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='branches.Branch'),
        ),
    ]
