# Generated by Django 2.2.4 on 2019-12-16 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_auto_20191210_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='uri',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=60, unique=True),
        ),
    ]
