# Generated by Django 2.1.4 on 2019-03-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_auto_20190216_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='branches.Branch'),
        ),
    ]
