# Generated by Django 2.2.4 on 2020-02-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_auto_20191216_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='direct_messages_accessibility',
            field=models.CharField(choices=[('FO', 'Following only'), ('EO', 'Everyone')], default='EO', max_length=2),
        ),
    ]
