# Generated by Django 2.1.4 on 2019-05-11 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_auto_20190320_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchRequest',
            fields=[
                ('type', models.CharField(blank=True, choices=[('add', 'Add'), ('remove', 'Remove')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('on hold', 'On hold')], max_length=20, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='branches.Branch')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='branches.Branch')),
            ],
        ),
    ]
