# Generated by Django 2.1.4 on 2019-05-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_branchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('on hold', 'On hold')], default='on hold', max_length=20),
        ),
    ]
