# Generated by Django 2.1.4 on 2019-05-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_auto_20190514_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchrequest',
            name='request_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='branches.Branch'),
        ),
        migrations.AlterField(
            model_name='branchrequest',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='branches.Branch'),
        ),
    ]
