# Generated by Django 2.1.4 on 2019-05-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_branchrequest_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='trending_score',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=14),
        ),
    ]
