# Generated by Django 2.1.4 on 2019-08-04 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0014_branch_trending_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='uri',
            field=models.CharField(default=uuid.uuid4, max_length=60, unique=True),
        ),
    ]
