# Generated by Django 2.1.4 on 2019-08-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_auto_20190804_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchrequest',
            unique_together={('request_to', 'request_from', 'type')},
        ),
    ]
