# Generated by Django 2.2.4 on 2019-12-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tags', '0002_genericstringtaggeditem_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericBigIntTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_genericbiginttaggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_genericbiginttaggeditem_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
