# Generated by Django 2.2.4 on 2019-12-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_genericbiginttaggeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericstringtaggeditem',
            name='object_id',
            field=models.UUIDField(db_index=True, verbose_name='Object id'),
        ),
    ]
