# Generated by Django 2.1.4 on 2019-02-15 15:37

import branchposts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0005_auto_20190106_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(default=branchposts.models.uuid_int, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=3000, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='branches.Branch')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_from', to='branches.Branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'id')},
        ),
    ]
