# Generated by Django 2.2.4 on 2019-09-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='original_image',
            field=models.ImageField(height_field='height', null=True, upload_to='static/original_images', width_field='width'),
        ),
    ]
