# Generated by Django 2.1.4 on 2019-02-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_auto_20190216_0156'),
        ('branchposts', '0002_auto_20190215_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='to',
            new_name='posted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='poster',
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('posted', 'id')},
        ),
    ]
