# Generated by Django 2.1.4 on 2019-04-05 21:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_auto_20190320_1748'),
        ('branchposts', '0003_auto_20190217_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacts', to='branches.Branch')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacts', to='branchposts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='branchposts.React')),
            ],
        ),
    ]
