# Generated by Django 2.2.4 on 2019-09-07 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0004_auto_20190907_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spread',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
