# Generated by Django 2.1.4 on 2019-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0004_react_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(related_name='_post_replies_+', to='branchposts.Post'),
        ),
    ]
