# Generated by Django 2.2.4 on 2019-09-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0005_auto_20190907_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spread',
            old_name='count',
            new_name='times',
        ),
    ]
