# Generated by Django 2.2.4 on 2019-12-09 23:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0007_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.GenericStringTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
