# Generated by Django 2.1.4 on 2019-04-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0007_auto_20190406_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, null=True, related_name='_post_replies_+', to='branchposts.Post'),
        ),
    ]
