# Generated by Django 2.1.4 on 2019-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0008_auto_20190408_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='replied_to', to='branchposts.Post'),
        ),
    ]
