# Generated by Django 2.2.4 on 2019-12-16 15:31

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0008_auto_20191210_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.GenericBigIntTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
