# Generated by Django 2.2.4 on 2020-02-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0009_auto_20191216_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=30000, null=True, verbose_name='Text'),
        ),
    ]
