# Generated by Django 2.1.4 on 2019-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0010_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('reply', 'Reply'), ('post', 'Post')], default='post', max_length=20, null=True),
        ),
    ]
