# Generated by Django 2.1.4 on 2019-05-06 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0014_post_hot_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='hot_score',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
