# Generated by Django 2.1.4 on 2019-05-10 16:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_auto_20190320_1748'),
        ('branchposts', '0017_auto_20190508_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='branches.Branch')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('reply', 'Reply'), ('post', 'Post'), ('spread', 'Spread')], default='post', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='spread',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='branchposts.Post'),
        ),
    ]
