# Generated by Django 2.1.4 on 2019-05-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_auto_20190517_1723'),
        ('branchposts', '0018_auto_20190510_1901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spread',
            unique_together={('post', 'branch')},
        ),
    ]
