# Generated by Django 2.1.4 on 2019-05-17 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0019_auto_20190517_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='spread',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
