# Generated by Django 2.1.4 on 2019-05-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0022_auto_20190521_0435'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spread',
            unique_together=set(),
        ),
    ]
