# Generated by Django 2.1.4 on 2019-05-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0023_auto_20190524_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(height_field='height', null=True, upload_to='images', width_field='width'),
        ),
    ]
