# Generated by Django 2.1.4 on 2019-05-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0024_auto_20190525_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=3000, null=True, verbose_name='Text'),
        ),
    ]
