# Generated by Django 2.1.4 on 2019-05-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0025_auto_20190525_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
    ]
