# Generated by Django 2.1.4 on 2019-06-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0027_postvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvideo',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
