# Generated by Django 2.1.4 on 2019-06-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0028_auto_20190617_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvideo',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postvideo',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='thumbnail',
            field=models.ImageField(height_field='height', null=True, upload_to='thumbnails', width_field='width'),
        ),
    ]
