# Generated by Django 2.1.4 on 2019-06-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0029_auto_20190621_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
