# Generated by Django 2.1.4 on 2019-07-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchposts', '0031_auto_20190708_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='react',
            name='type',
            field=models.CharField(blank=True, choices=[('star', 'Star'), ('dislike', 'Dislike')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='react',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='branchposts.React'),
        ),
    ]
