# Generated by Django 2.0 on 2018-11-06 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_group_group_messages'),
        ('groupchat', '0002_auto_20181106_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='group_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groupchat.GroupChat'),
        ),
    ]
