# Generated by Django 2.0 on 2018-11-06 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0004_auto_20181106_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='group_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='groupchat.GroupChat'),
        ),
    ]
