# Generated by Django 2.0 on 2018-11-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_remove_group_group_chat'),
        ('groupchat', '0006_auto_20181106_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='name',
            field=models.CharField(default='general', max_length=25),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='type',
            field=models.CharField(choices=[('BR', 'Branch'), ('LF', 'Leaf')], default='BR', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='groupchat',
            unique_together={('group', 'name')},
        ),
    ]
