# Generated by Django 2.0 on 2018-11-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0007_auto_20181107_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='group_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groupchat.GroupMessage'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='groupchat.GroupChat'),
        ),
    ]
