# Generated by Django 2.0 on 2018-11-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0008_auto_20181107_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='group_message',
        ),
    ]
