# Generated by Django 2.0 on 2018-11-07 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0009_remove_groupchat_group_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='group_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groupchat.GroupChat'),
        ),
    ]
