# Generated by Django 2.0 on 2018-07-30 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_auto_20180729_2304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('owner', 'name')},
        ),
    ]
