# Generated by Django 2.0 on 2018-08-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180730_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='No description.', max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
