# Generated by Django 2.0 on 2018-08-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20180802_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='over_18',
            field=models.BooleanField(default=False),
        ),
    ]
