# Generated by Django 2.0 on 2018-08-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_over_18'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='accessibility',
            field=models.CharField(choices=[('PU', 'Public'), ('IO', 'Invite only')], default='PU', max_length=2),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='No description.', max_length=200),
        ),
    ]
