# Generated by Django 2.0 on 2018-08-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parents',
            field=models.ManyToManyField(related_name='children', to='groups.Group'),
        ),
    ]
