# Generated by Django 2.0 on 2018-08-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_group_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='groups.Group'),
        ),
    ]
