# Generated by Django 2.0 on 2018-08-16 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0012_auto_20180810_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='unnamed', max_length=30)),
                ('accessibility', models.CharField(choices=[('PU', 'Public'), ('IO', 'Invite only')], default='PU', max_length=2)),
                ('description', models.TextField(default='No description.', max_length=200)),
                ('over_18', models.BooleanField(default=False)),
                ('tag', models.IntegerField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('group_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupss', to=settings.AUTH_USER_MODEL)),
                ('parents', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='groups.TreeGroup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='treegroup',
            unique_together={('group_owner', 'name')},
        ),
    ]
