# Generated by Django 2.0 on 2018-08-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_auto_20180816_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treegroup',
            old_name='parents',
            new_name='parent',
        ),
    ]
