# Generated by Django 2.0 on 2018-08-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_auto_20180816_2323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='treegroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='treegroup',
            name='group_owner',
        ),
        migrations.RemoveField(
            model_name='treegroup',
            name='parent',
        ),
        migrations.DeleteModel(
            name='TreeGroup',
        ),
    ]
