# Generated by Django 2.0 on 2018-10-13 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_auto_20181013_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='uri',
            field=models.CharField(default=uuid.uuid4, max_length=60),
        ),
    ]
