# Generated by Django 2.0 on 2018-10-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_group_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='group_banner',
            field=models.ImageField(default='images/group_banners/default.jpeg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='group_image',
            field=models.ImageField(default='images/group_images/default.jpeg', upload_to='images'),
        ),
    ]
