# Generated by Django 2.0 on 2018-10-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_auto_20181031_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='group_banner',
            field=models.ImageField(default='images/group_banners/default.jpeg', upload_to='images/group_banners/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group_image',
            field=models.ImageField(default='images/group_images/default.jpeg', upload_to='images/group_images'),
        ),
    ]
