# Generated by Django 2.0 on 2018-10-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_auto_20181031_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group_banner',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='group_image',
        ),
        migrations.AddField(
            model_name='group',
            name='group_banner',
            field=models.ImageField(default='/images/group_images/banner/default.jpeg', upload_to='images/group_images/banner'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(default='/images/group_images/profile/default.jpeg', upload_to='images/group_images/profile'),
        ),
    ]
