# Generated by Django 2.0 on 2018-11-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_auto_20181031_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
