# Generated by Django 2.0 on 2018-11-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_auto_20181106_1710'),
        ('groups', '0023_group_group_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_messages',
        ),
        migrations.AddField(
            model_name='group',
            name='group_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='groupchat.GroupChat'),
        ),
    ]
