# Generated by Django 2.0 on 2018-11-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_auto_20181106_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_chat',
        ),
    ]
